// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlDUW1nobm83FR88oGJ6ydxQ4WUHl629o',
    appId: '1:7676172075:web:9ab504ddd974e3d529d76e',
    messagingSenderId: '7676172075',
    projectId: 'backend-yk123',
    authDomain: 'backend-yk123.firebaseapp.com',
    storageBucket: 'backend-yk123.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2_w-BoM8ysK1r1AJCzivD9P76ZpIEPqk',
    appId: '1:7676172075:android:2d985d7aa4b50af629d76e',
    messagingSenderId: '7676172075',
    projectId: 'backend-yk123',
    storageBucket: 'backend-yk123.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb_Qe_v8mWnxWQUoSj815XmmVaINDA1v8',
    appId: '1:7676172075:ios:f4b7e14fb7ad0a5029d76e',
    messagingSenderId: '7676172075',
    projectId: 'backend-yk123',
    storageBucket: 'backend-yk123.appspot.com',
    iosClientId: '7676172075-tkc40dtqusu1qirlkic6qs2s6gke9b6r.apps.googleusercontent.com',
    iosBundleId: 'com.yousuf.backend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb_Qe_v8mWnxWQUoSj815XmmVaINDA1v8',
    appId: '1:7676172075:ios:f4b7e14fb7ad0a5029d76e',
    messagingSenderId: '7676172075',
    projectId: 'backend-yk123',
    storageBucket: 'backend-yk123.appspot.com',
    iosClientId: '7676172075-tkc40dtqusu1qirlkic6qs2s6gke9b6r.apps.googleusercontent.com',
    iosBundleId: 'com.yousuf.backend',
  );
}
